import * as actions from "spiders-wm/actions";
import type { BindingsConfig } from "spiders-wm/config";

export const bindings = {
  mod: "super",
  entries: [
    { bind: ["mod", "Return"], action: actions.spawn("foot") },
    { bind: ["mod", "d"], action: actions.spawn("rofi -show drun") },
    { bind: ["mod", "h"], action: actions.focus_dir("left") },
    { bind: ["mod", "j"], action: actions.focus_dir("down") },
    { bind: ["mod", "k"], action: actions.focus_dir("up") },
    { bind: ["mod", "l"], action: actions.focus_dir("right") },
    { bind: ["mod", "shift", "h"], action: actions.swap_dir("left") },
    { bind: ["mod", "shift", "j"], action: actions.swap_dir("down") },
    { bind: ["mod", "shift", "k"], action: actions.swap_dir("up") },
    { bind: ["mod", "shift", "l"], action: actions.swap_dir("right") },
    { bind: ["mod", "ctrl", "h"], action: actions.resize_dir("left") },
    { bind: ["mod", "ctrl", "j"], action: actions.resize_dir("down") },
    { bind: ["mod", "ctrl", "k"], action: actions.resize_dir("up") },
    { bind: ["mod", "ctrl", "l"], action: actions.resize_dir("right") },
    { bind: ["mod", "ctrl", "shift", "h"], action: actions.resize_tiled("left") },
    { bind: ["mod", "ctrl", "shift", "j"], action: actions.resize_tiled("down") },
    { bind: ["mod", "ctrl", "shift", "k"], action: actions.resize_tiled("up") },
    { bind: ["mod", "ctrl", "shift", "l"], action: actions.resize_tiled("right") },
    { bind: ["mod", "q"], action: actions.kill_client() },
    { bind: ["mod", "shift", "r"], action: actions.reload_config() },
    { bind: ["mod", "f"], action: actions.toggle_fullscreen() },
    { bind: ["mod", "space"], action: actions.cycle_layout() },
    { bind: ["mod", "shift", "space"], action: actions.toggle_floating() },
    { bind: ["mod", "comma"], action: actions.focus_mon_left() },
    { bind: ["mod", "period"], action: actions.focus_mon_right() },
    { bind: ["mod", "shift", "comma"], action: actions.send_mon_left() },
    { bind: ["mod", "shift", "period"], action: actions.send_mon_right() },
    { bind: ["mod", "shift", "Left"], action: actions.move("left") },
    { bind: ["mod", "shift", "Right"], action: actions.move("right") },
    { bind: ["mod", "shift", "Up"], action: actions.move("up") },
    { bind: ["mod", "shift", "Down"], action: actions.move("down") },
    { bind: ["mod", "ctrl", "Left"], action: actions.resize("left") },
    { bind: ["mod", "ctrl", "Right"], action: actions.resize("right") },
    { bind: ["mod", "ctrl", "Up"], action: actions.resize("up") },
    { bind: ["mod", "ctrl", "Down"], action: actions.resize("down") },
    { bind: ["mod", "1"], action: actions.view_workspace(1) },
    { bind: ["mod", "2"], action: actions.view_workspace(2) },
    { bind: ["mod", "3"], action: actions.view_workspace(3) },
    { bind: ["mod", "4"], action: actions.view_workspace(4) },
    { bind: ["mod", "5"], action: actions.view_workspace(5) },
    { bind: ["mod", "6"], action: actions.view_workspace(6) },
    { bind: ["mod", "7"], action: actions.view_workspace(7) },
    { bind: ["mod", "8"], action: actions.view_workspace(8) },
    { bind: ["mod", "9"], action: actions.view_workspace(9) },
    { bind: ["mod", "ctrl", "1"], action: actions.toggle_view_workspace(1) },
    { bind: ["mod", "ctrl", "2"], action: actions.toggle_view_workspace(2) },
    { bind: ["mod", "ctrl", "3"], action: actions.toggle_view_workspace(3) },
    { bind: ["mod", "ctrl", "4"], action: actions.toggle_view_workspace(4) },
    { bind: ["mod", "ctrl", "5"], action: actions.toggle_view_workspace(5) },
    { bind: ["mod", "ctrl", "6"], action: actions.toggle_view_workspace(6) },
    { bind: ["mod", "ctrl", "7"], action: actions.toggle_view_workspace(7) },
    { bind: ["mod", "ctrl", "8"], action: actions.toggle_view_workspace(8) },
    { bind: ["mod", "ctrl", "9"], action: actions.toggle_view_workspace(9) },
    { bind: ["mod", "shift", "1"], action: actions.assign_workspace(1) },
    { bind: ["mod", "shift", "2"], action: actions.assign_workspace(2) },
    { bind: ["mod", "shift", "3"], action: actions.assign_workspace(3) },
    { bind: ["mod", "shift", "4"], action: actions.assign_workspace(4) },
    { bind: ["mod", "shift", "5"], action: actions.assign_workspace(5) },
    { bind: ["mod", "shift", "6"], action: actions.assign_workspace(6) },
    { bind: ["mod", "shift", "7"], action: actions.assign_workspace(7) },
    { bind: ["mod", "shift", "8"], action: actions.assign_workspace(8) },
    { bind: ["mod", "shift", "9"], action: actions.assign_workspace(9) },
    { bind: ["mod", "ctrl", "shift", "1"], action: actions.toggle_workspace(1) },
    { bind: ["mod", "ctrl", "shift", "2"], action: actions.toggle_workspace(2) },
    { bind: ["mod", "ctrl", "shift", "3"], action: actions.toggle_workspace(3) },
    { bind: ["mod", "ctrl", "shift", "4"], action: actions.toggle_workspace(4) },
    { bind: ["mod", "ctrl", "shift", "5"], action: actions.toggle_workspace(5) },
    { bind: ["mod", "ctrl", "shift", "6"], action: actions.toggle_workspace(6) },
    { bind: ["mod", "ctrl", "shift", "7"], action: actions.toggle_workspace(7) },
    { bind: ["mod", "ctrl", "shift", "8"], action: actions.toggle_workspace(8) },
    { bind: ["mod", "ctrl", "shift", "9"], action: actions.toggle_workspace(9) },
  ],
} satisfies BindingsConfig;
