import * as commands from "@spiders-wm/sdk/commands";
import type { BindingsConfig } from "@spiders-wm/sdk/config";

export const bindings = {
  mod: "alt",
  entries: [
    { bind: ["mod", "Return"], command: commands.spawn("foot") },
    { bind: ["mod", "d"], command: commands.spawn("rofi -show drun") },
    { bind: ["mod", "h"], command: commands.focus_dir("left") },
    { bind: ["mod", "j"], command: commands.focus_dir("down") },
    { bind: ["mod", "k"], command: commands.focus_dir("up") },
    { bind: ["mod", "l"], command: commands.focus_dir("right") },
    { bind: ["mod", "shift", "h"], command: commands.swap_dir("left") },
    { bind: ["mod", "shift", "j"], command: commands.swap_dir("down") },
    { bind: ["mod", "shift", "k"], command: commands.swap_dir("up") },
    { bind: ["mod", "shift", "l"], command: commands.swap_dir("right") },
    { bind: ["mod", "ctrl", "h"], command: commands.resize_dir("left") },
    { bind: ["mod", "ctrl", "j"], command: commands.resize_dir("down") },
    { bind: ["mod", "ctrl", "k"], command: commands.resize_dir("up") },
    { bind: ["mod", "ctrl", "l"], command: commands.resize_dir("right") },
    {
      bind: ["mod", "ctrl", "shift", "h"],
      command: commands.resize_tiled("left"),
    },
    {
      bind: ["mod", "ctrl", "shift", "j"],
      command: commands.resize_tiled("down"),
    },
    {
      bind: ["mod", "ctrl", "shift", "k"],
      command: commands.resize_tiled("up"),
    },
    {
      bind: ["mod", "ctrl", "shift", "l"],
      command: commands.resize_tiled("right"),
    },
    { bind: ["mod", "q"], command: commands.kill_client() },
    { bind: ["mod", "shift", "r"], command: commands.reload_config() },
    { bind: ["mod", "f"], command: commands.toggle_fullscreen() },
    { bind: ["mod", "space"], command: commands.cycle_layout() },
    { bind: ["mod", "shift", "space"], command: commands.toggle_floating() },
    { bind: ["mod", "comma"], command: commands.focus_mon_left() },
    { bind: ["mod", "period"], command: commands.focus_mon_right() },
    { bind: ["mod", "shift", "comma"], command: commands.send_mon_left() },
    { bind: ["mod", "shift", "period"], command: commands.send_mon_right() },
    { bind: ["mod", "shift", "Left"], command: commands.move("left") },
    { bind: ["mod", "shift", "Right"], command: commands.move("right") },
    { bind: ["mod", "shift", "Up"], command: commands.move("up") },
    { bind: ["mod", "shift", "Down"], command: commands.move("down") },
    { bind: ["mod", "ctrl", "Left"], command: commands.resize("left") },
    { bind: ["mod", "ctrl", "Right"], command: commands.resize("right") },
    { bind: ["mod", "ctrl", "Up"], command: commands.resize("up") },
    { bind: ["mod", "ctrl", "Down"], command: commands.resize("down") },
    { bind: ["mod", "1"], command: commands.view_workspace(1) },
    { bind: ["mod", "2"], command: commands.view_workspace(2) },
    { bind: ["mod", "3"], command: commands.view_workspace(3) },
    { bind: ["mod", "4"], command: commands.view_workspace(4) },
    { bind: ["mod", "5"], command: commands.view_workspace(5) },
    { bind: ["mod", "6"], command: commands.view_workspace(6) },
    { bind: ["mod", "7"], command: commands.view_workspace(7) },
    { bind: ["mod", "8"], command: commands.view_workspace(8) },
    { bind: ["mod", "9"], command: commands.view_workspace(9) },
    { bind: ["mod", "ctrl", "1"], command: commands.toggle_view_workspace(1) },
    { bind: ["mod", "ctrl", "2"], command: commands.toggle_view_workspace(2) },
    { bind: ["mod", "ctrl", "3"], command: commands.toggle_view_workspace(3) },
    { bind: ["mod", "ctrl", "4"], command: commands.toggle_view_workspace(4) },
    { bind: ["mod", "ctrl", "5"], command: commands.toggle_view_workspace(5) },
    { bind: ["mod", "ctrl", "6"], command: commands.toggle_view_workspace(6) },
    { bind: ["mod", "ctrl", "7"], command: commands.toggle_view_workspace(7) },
    { bind: ["mod", "ctrl", "8"], command: commands.toggle_view_workspace(8) },
    { bind: ["mod", "ctrl", "9"], command: commands.toggle_view_workspace(9) },
    { bind: ["mod", "shift", "1"], command: commands.assign_workspace(1) },
    { bind: ["mod", "shift", "2"], command: commands.assign_workspace(2) },
    { bind: ["mod", "shift", "3"], command: commands.assign_workspace(3) },
    { bind: ["mod", "shift", "4"], command: commands.assign_workspace(4) },
    { bind: ["mod", "shift", "5"], command: commands.assign_workspace(5) },
    { bind: ["mod", "shift", "6"], command: commands.assign_workspace(6) },
    { bind: ["mod", "shift", "7"], command: commands.assign_workspace(7) },
    { bind: ["mod", "shift", "8"], command: commands.assign_workspace(8) },
    { bind: ["mod", "shift", "9"], command: commands.assign_workspace(9) },
    {
      bind: ["mod", "ctrl", "shift", "1"],
      command: commands.toggle_workspace(1),
    },
    {
      bind: ["mod", "ctrl", "shift", "2"],
      command: commands.toggle_workspace(2),
    },
    {
      bind: ["mod", "ctrl", "shift", "3"],
      command: commands.toggle_workspace(3),
    },
    {
      bind: ["mod", "ctrl", "shift", "4"],
      command: commands.toggle_workspace(4),
    },
    {
      bind: ["mod", "ctrl", "shift", "5"],
      command: commands.toggle_workspace(5),
    },
    {
      bind: ["mod", "ctrl", "shift", "6"],
      command: commands.toggle_workspace(6),
    },
    {
      bind: ["mod", "ctrl", "shift", "7"],
      command: commands.toggle_workspace(7),
    },
    {
      bind: ["mod", "ctrl", "shift", "8"],
      command: commands.toggle_workspace(8),
    },
    {
      bind: ["mod", "ctrl", "shift", "9"],
      command: commands.toggle_workspace(9),
    },
  ],
} satisfies BindingsConfig;
