complete -c spiders-cli -l json -d 'emit JSON output'
complete -c spiders-cli -l socket -r -d 'path to WM IPC socket'
complete -c spiders-cli -f -n 'not __fish_seen_subcommand_from config wm completions' -a 'config wm completions'
complete -c spiders-cli -n '__fish_seen_subcommand_from config' -a 'discover check build'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and not __fish_seen_subcommand_from query command monitor debug smoke' -a 'query command monitor debug smoke'
complete -c spiders-cli -n '__fish_seen_subcommand_from completions' -a 'zsh bash fish'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from debug; and not __fish_seen_subcommand_from dump' -a 'dump'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from query' -a 'state' -d 'full compositor state snapshot'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from query' -a 'focused-window' -d 'currently focused window'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from query' -a 'current-output' -d 'currently focused output'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from query' -a 'current-workspace' -d 'currently focused workspace'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from query' -a 'monitor-list' -d 'list outputs and geometry'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from query' -a 'workspace-names' -d 'configured workspace names'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from command' -a 'close-focused-window' -d 'close the currently focused window'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from command' -a 'toggle-floating' -d 'toggle floating mode on focused window'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from command' -a 'toggle-fullscreen' -d 'toggle fullscreen on focused window'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from command' -a 'reload-config' -d 'reload window manager config'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from command' -a 'focus-next-window' -d 'focus next window in stack'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from command' -a 'focus-previous-window' -d 'focus previous window in stack'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from command' -a 'select-next-workspace' -d 'focus next workspace'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from command' -a 'select-previous-workspace' -d 'focus previous workspace'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from command' -a 'cycle-layout-next' -d 'switch to next layout'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from command' -a 'cycle-layout-previous' -d 'switch to previous layout'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from command' -a 'focus-left' -d 'focus window to the left'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from command' -a 'focus-right' -d 'focus window to the right'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from command' -a 'focus-up' -d 'focus window above'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from command' -a 'focus-down' -d 'focus window below'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from command' -a 'set-layout:<name>' -d 'activate a layout by name'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from command' -a 'select-workspace:<id>' -d 'focus a workspace by id'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from command' -a 'spawn:<command>' -d 'spawn an external process'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from monitor' -a 'all' -d 'all event topics'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from monitor' -a 'focus' -d 'focus events'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from monitor' -a 'windows' -d 'window lifecycle and mode events'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from monitor' -a 'workspaces' -d 'workspace and output events'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from monitor' -a 'layout' -d 'layout change events'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from monitor' -a 'config' -d 'config reload events'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from dump' -a 'wm-state' -d 'dump compositor state'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from dump' -a 'debug-profile' -d 'dump debug profiling data'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from dump' -a 'scene-snapshot' -d 'dump current scene snapshot'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from dump' -a 'frame-sync' -d 'dump frame sync information'
complete -c spiders-cli -n '__fish_seen_subcommand_from wm; and __fish_seen_subcommand_from dump' -a 'seats' -d 'dump input seat information'
